### ISSUE TITLE
prepare_data.sh throws path errors

### ISSUE THREAD

**Issue by eyildiz-ugoe** [liyi14/mx-DeepIM#13]
I followed the instructions and I have the following paths set up:

```
/data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/ape, benchviseblue, ...
/data/LINEMOD_6D/LM6d_converted/LM6d_refine/image_set/observed/ape_all.txt, ...
/data/LINEMOD_6D/LM6d_converted/LM6d_refine/PoseCNN_LINEMOD_6D_results/ape, ...
```

`/data/LM6d_origin/test/01,...`

and when I run `sh prepare_data.sh` from the root folder, I get:

```
Traceback (most recent call last):
  File "toolkit/LM6d_devkit/LM6d_2a_adapt_images.py", line 183, in <module>
    main()
  File "toolkit/LM6d_devkit/LM6d_2a_adapt_images.py", line 98, in main
    '{:02d}'.format(class2idx(cls_name)), 'rgb')) if '.png' in fn]
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/workspace/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_origin/test/01/rgb'
target path: /home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/gt_observed
1 ape
self.window:  <GLFW.Window object at 0x7f76ca4aeeb8>
self.render_kernel at init:  <glumpy.gloo.program.Program object at 0x7f76ce5f8ba8>
  0%|                                                                                                                                             | 0/1236 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "toolkit/LM6d_0_gen_gt_observed.py", line 172, in <module>
    gen_gt_observed()
  File "toolkit/LM6d_0_gen_gt_observed.py", line 97, in gen_gt_observed
    meta_data = sio.loadmat(observed_meta_path)
  File "/home/username/.local/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/username/.local/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable
target path: /home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/rendered_poses
angle_std=15.0, angle_max=45.0, x_std=0.01, y_std=0.01, z_std=0.05
1 ape
  0%|                                                                                                                                             | 0/1236 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "toolkit/LM6d_1_gen_rendered_pose.py", line 80, in <module>
    src_pose_m = np.loadtxt(pose_path, skiprows=1)
  File "/home/username/.local/lib/python3.5/site-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/username/.local/lib/python3.5/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/username/.local/lib/python3.5/site-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
OSError: /home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/gt_observed/ape/000001-pose.txt not found.
target path: /home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/rendered
target path: /home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/image_set
start  ape
self.window:  <GLFW.Window object at 0x7f0b9446dda0>
self.render_kernel at init:  <glumpy.gloo.program.Program object at 0x7f0bbbbfc4a8>
Traceback (most recent call last):
  File "toolkit/LM6d_2_gen_rendered.py", line 181, in <module>
    main()
  File "toolkit/LM6d_2_gen_rendered.py", line 86, in main
    with open(rendered_pose_path.format(set_type, class_name)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/rendered_poses/LM6d_all_rendered_pose_ape.txt'
Traceback (most recent call last):
  File "toolkit/LM6d_3_gen_PoseCNN_pred_rendered.py", line 13, in <module>
    from lib.render_glumpy.render_py import Render_Py
  File "/home/username/workspace/mx-DeepIM/toolkit/../lib/render_glumpy/render_py.py", line 8, in <module>
    from glumpy import app, gl, gloo, glm, data, log
ImportError: No module named glumpy
####### Prepare LM6d_refine_syn ########
/home/username/workspace/mx-DeepIM
target path: /home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/poses
  0%|                                                                                                                                              | 0/186 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "toolkit/LM6d_ds_0_gen_observed_poses.py", line 239, in <module>
    gen_poses()
  File "toolkit/LM6d_ds_0_gen_observed_poses.py", line 169, in gen_poses
    pose_dict, quat_stat, trans_stat, new_points = stat_poses()
  File "toolkit/LM6d_ds_0_gen_observed_poses.py", line 98, in stat_poses
    assert os.path.exists(pose_path), 'path {} not exists'.format(pose_path)
AssertionError: path /home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/gt_observed/ape/000005-pose.txt not exists
Traceback (most recent call last):
  File "toolkit/LM6d_ds_1_gen_observed.py", line 173, in <module>
    gen_observed()
  File "toolkit/LM6d_ds_1_gen_observed.py", line 70, in gen_observed
    with open(syn_poses_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/poses/LM6d_ds_train_observed_pose_all.pkl'
Traceback (most recent call last):
  File "toolkit/LM6d_ds_2_gen_gt_observed.py", line 164, in <module>
    gen_gt_observed()
  File "toolkit/LM6d_ds_2_gen_gt_observed.py", line 68, in gen_gt_observed
    with open(syn_poses_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/poses/LM6d_ds_train_observed_pose_all.pkl'
15.0 45.0 0.01 0.01 0.05
Traceback (most recent call last):
  File "toolkit/LM6d_ds_3_gen_rendered_pose.py", line 80, in <module>
    with open(sel_set_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/image_set/observed/LM6d_data_syn_train_observed_ape.txt'
start  0 ape
self.window:  <GLFW.Window object at 0x7f755bbbff60>
self.render_kernel at init:  <glumpy.gloo.program.Program object at 0x7f758323e908>
Traceback (most recent call last):
  File "toolkit/LM6d_ds_4_gen_rendered.py", line 89, in <module>
    with open(observed_list_path.format(set_type, class_name)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/workspace/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/image_set/observed/LM6d_data_syn_train_observed_ape.txt'

```

Any thoughts?

**Comment by wangg12** [comment]
@eyildiz-ugoe It seems `/data/LM6d_origin/test/01,...` should be `/data/LINEMOD_6D/LM6d_origin/test/01,...`

**Comment by liyi14** [comment]
Yes, it is a typo. Sorry about that.
