### ISSUE TITLE
Error in prepare_data.sh

### ISSUE THREAD

**Issue by 08ME3303** [liyi14/mx-DeepIM#15]
Hi,

I am trying to run prepare_data.sh. After successfully completing everything till LM6D_ds_2_gen_rendered.py, I am getting the following error:

Traceback (most recent call last):
  File "toolkit/LM6d_ds_3_gen_rendered_pose.py", line 80, in <module>
    with open(sel_set_file) as f:
IOError: [Errno 2] No such file or directory: '/home/dp18-29/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/image_set/observed/LM6d_data_syn_train_observed_ape.txt'
('/home/dp18-29/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/data/rendered', 'FINNS ?????????????????', True)
('/home/dp18-29/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/image_set', 'FINNS ?????????????????', True)
start  0 ape
self.window:  <GLFW.Window object at 0x7f931dcaadd0>
self.render_kernel at init:  <glumpy.gloo.program.Program object at 0x7f9313e1d750>
Traceback (most recent call last):
  File "toolkit/LM6d_ds_4_gen_rendered.py", line 89, in <module>
    with open(observed_list_path.format(set_type, class_name)) as f:
IOError: [Errno 2] No such file or directory: '/home/dp18-29/mx-DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/image_set/observed/LM6d_data_syn_train_observed_ape.txt'

Any idea how to proceed?

**Comment by 08ME3303** [comment]
Got fixed! :)
