### ISSUE TITLE
Wrong shape while training on ape

### ISSUE THREAD

**Issue by 08ME3303** [liyi14/mx-DeepIM#16]
Hi,

We are trying to run the train_and_test_ape.sh and we get the following error:

`Traceback (most recent call last):
  File "experiments/deepim/deepim_test.py", line 20, in <module>
    test.main()
  File "experiments/deepim/../../deepim/test.py", line 132, in main
    test_deepim()
  File "experiments/deepim/../../deepim/test.py", line 113, in test_deepim
    sym_instance.check_parameter_shapes(arg_params, aux_params, data_shape_dict, is_train=False)
  File "experiments/deepim/../../lib/utils/symbol.py", line 49, in check_parameter_shapes
    arg_params[k].shape)
AssertionError: shape inconsistent for flow_conv1_weight inferred (64L, 8L, 7L, 7L) provided (64L, 6L, 7L, 7L)
`
The flownet pretrained model was downloaded from the Google drive and placed in ${MXNET_ROOT}/model/pretrained_models

Any ideas on how to proceed?

**Comment by wangg12** [comment]
Have you finished training the model?

**Comment by 08ME3303** [comment]
Yeah, the model finished training.

**Comment by 08ME3303** [comment]
That problem got sorted, now getting this error:

***********Finish loading models************ 
self.window:  <GLFW.Window object at 0x7f38e83065d0> 
self.render_kernel at init:  [<glumpy.gloo.program.Program object at 0x7f38e8306e10>] 
**************setup render_glumpy environment succeed ***************** 
Traceback (most recent call last): 
  File "experiments/deepim/deepim_train_test.py", line 21, in <module> 
    test.main() 
  File "experiments/deepim/../../deepim/test.py", line 133, in main 
    test_deepim() 
  File "experiments/deepim/../../deepim/test.py", line 128, in test_deepim 
    pred_eval(config, predictor, test_data, imdb_test, vis=args.vis, ignore_cache=args.ignore_cache, logger=logger, pairdb=pairdb) 
  File "experiments/deepim/../../deepim/core/tester.py", line 347, in pred_eval 
    class_id = imdb_test.classes.index(pairdb[idx]['gt_class']) 
ValueError: 'ape' is not in list
