### ISSUE TITLE
vis, vis_video, vis_video_zoom in test.py

### ISSUE THREAD

**Issue by thomastangucb** [liyi14/mx-DeepIM#25]
Thanks for the great work!

In test.py, there are several argument options:  --vis, --vis_video, --vis_video_zoom. I tried to visualize your work by enabling these options, but no picture nor video was generated. 

Could you share more information about these visualization options? Thanks.

**Comment by Cryptiex** [comment]
When calling test.py with the --vis flag the following error pops up:

***************setup render_glumpy environment succeed ******************
not using render_real depth in par_generate_gt
Traceback (most recent call last):
  File "experiments/deepim/deepim_test.py", line 20, in <module>
    test.main()
  File "experiments/deepim/../../deepim/test.py", line 210, in main
    test_deepim()
  File "experiments/deepim/../../deepim/test.py", line 203, in test_deepim
    pairdb=pairdb,
  File "experiments/deepim/../../deepim/core/tester.py", line 521, in pred_eval
    flow_gt = par_generate_gt(config, pairdb[idx])
  File "experiments/deepim/../../deepim/core/tester.py", line 752, in par_generate_gt
    pair_rec["depth_real"], cv2.IMREAD_UNCHANGED
KeyError: 'depth_real'

**Comment by wangg12** [comment]
@Cryptiex The key name might be refactored to `depth_observed`, since `observed` is `real`.

**Comment by Cryptiex** [comment]
Thanks for the fast reply! Your solution solved my problem. However, another problem now occurs a few lines later:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-8cb2e2389c11>", line 1, in <module>
    runfile('/media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM-master/deepim/test.py', args='--cfg experiments/deepim/cfgs/deepim_flownet_LM_SIXD_v1_ape_RFMx4_8epoch.yaml --gpus 0 --vis', wdir='/media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM-master')
  File "/home/deeplearner/pycharm-2018.2.4/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/deeplearner/pycharm-2018.2.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM-master/deepim/test.py", line 214, in <module>
    main()
  File "/media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM-master/deepim/test.py", line 210, in main
    test_deepim()
  File "/media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM-master/deepim/test.py", line 203, in test_deepim
    pairdb=pairdb,
  File "/media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM-master/deepim/core/tester.py", line 521, in pred_eval
    flow_gt = par_generate_gt(config, pairdb[idx])
  File "/media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM-master/deepim/core/tester.py", line 767, in par_generate_gt
    if config.network.FLOW_I2R:
AttributeError: 'EasyDict' object has no attribute 'FLOW_I2R'

**Comment by wangg12** [comment]
@Cryptiex Emmmm. You could simply change `FLOW_I2R` terms to `True`, and delete those `FLOW_R2I`. `I2R` means `rendered to observed (i.e., imagine to real)`.

**Comment by Cryptiex** [comment]
There still seem to be some errors when trying to visualize the testing process. There are like 4-5 undefined config parameters and dict keys. Maybe you can have a closer look at this problem, since this does not seem to be desired behavior of the implementation.
Thanks a lot.

**Comment by wangg12** [comment]
@Cryptiex Now the errors should be gone. However, you still need to add some code to visualize the updated pose (e.g. by using the updated rendered color/depth and the updated pose_est). It should be easy. The visualization is out of scope of this repo.
