### ISSUE TITLE
Fatal Python error: Couldn't create autoTSSkey mapping

### ISSUE THREAD

**Issue by lh641446825** [liyi14/mx-DeepIM#28]
When I run sh prepare_data.sh from the root folder, I get:

************Finish loading models*************
Fatal Python error: Couldn't create autoTSSkey mapping

Thread 0x00007f5bcb029740 (most recent call first):
  File "/home/anaconda3/lib/python3.7/site-packages/glumpy/app/window/backends/backend_glfw.py", line 213 in __init__
  File "/home/anaconda3/lib/python3.7/site-packages/glumpy/app/__init__.py", line 187 in __new__
  File "/home/Workspace/Project/DeepIM/toolkit/LM6d_devkit/../../lib/render_glumpy/render_py_multi.py", line 92 in __init__
  File "toolkit/LM6d_devkit/LM6d_2a_adapt_images.py", line 104 in main
  File "toolkit/LM6d_devkit/LM6d_2a_adapt_images.py", line 211 in <module>
Aborted (core dumped)
target path: /home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/gt_observed
1 ape
Traceback (most recent call last):
  File "toolkit/LM6d_0_gen_gt_observed.py", line 198, in <module>
    gen_gt_observed()
  File "toolkit/LM6d_0_gen_gt_observed.py", line 91, in gen_gt_observed
    'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/image_set/observed/ape_all.txt'
target path: /home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/rendered_poses
angle_std=15.0, angle_max=45.0, x_std=0.01, y_std=0.01, z_std=0.05
1 ape
Traceback (most recent call last):
  File "toolkit/LM6d_1_gen_rendered_pose.py", line 72, in <module>
    with open(sel_set_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/image_set/observed/ape_all.txt'
target path: /home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/rendered
target path: /home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/image_set
start  1 ape
Fatal Python error: Couldn't create autoTSSkey mapping

Thread 0x00007fde47315740 (most recent call first):
  File "/home/anaconda3/lib/python3.7/site-packages/glumpy/app/window/backends/backend_glfw.py", line 213 in __init__
  File "/home/anaconda3/lib/python3.7/site-packages/glumpy/app/__init__.py", line 187 in __new__
  File "/home/Workspace/Project/DeepIM/toolkit/../lib/render_glumpy/render_py.py", line 81 in __init__
  File "toolkit/LM6d_2_gen_rendered.py", line 76 in main
  File "toolkit/LM6d_2_gen_rendered.py", line 205 in <module>
Aborted (core dumped)
Fatal Python error: Couldn't create autoTSSkey mapping

Thread 0x00007f412c378740 (most recent call first):
  File "/home/anaconda3/lib/python3.7/site-packages/glumpy/app/window/backends/backend_glfw.py", line 213 in __init__
  File "/home/anaconda3/lib/python3.7/site-packages/glumpy/app/__init__.py", line 187 in __new__
  File "/home/Workspace/Project/DeepIM/toolkit/../lib/render_glumpy/render_py.py", line 81 in __init__
  File "toolkit/LM6d_3_gen_PoseCNN_pred_rendered.py", line 91 in <module>
Aborted (core dumped)
####### Prepare LM6d_refine_syn ########
/home/Workspace/Project/DeepIM
target path: /home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/poses
  0%|                                                                                     | 0/1236 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "toolkit/LM6d_ds_0_gen_observed_poses.py", line 266, in <module>
    gen_poses()
  File "toolkit/LM6d_ds_0_gen_observed_poses.py", line 189, in gen_poses
    pose_dict, quat_stat, trans_stat, new_points = stat_poses()
  File "toolkit/LM6d_ds_0_gen_observed_poses.py", line 109, in stat_poses
    pose_path)
AssertionError: path /home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/gt_observed/ape/000001-pose.txt not exists
Traceback (most recent call last):
  File "toolkit/LM6d_ds_1_gen_observed.py", line 185, in <module>
    gen_observed()
  File "toolkit/LM6d_ds_1_gen_observed.py", line 76, in gen_observed
    with open(syn_poses_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/poses/LM6d_ds_train_observed_pose_all.pkl'
Traceback (most recent call last):
  File "toolkit/LM6d_ds_2_gen_gt_observed.py", line 178, in <module>
    gen_gt_observed()
  File "toolkit/LM6d_ds_2_gen_gt_observed.py", line 75, in gen_gt_observed
    with open(syn_poses_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/poses/LM6d_ds_train_observed_pose_all.pkl'
15.0 45.0 0.01 0.01 0.05
Traceback (most recent call last):
  File "toolkit/LM6d_ds_3_gen_rendered_pose.py", line 85, in <module>
    with open(sel_set_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/Workspace/Project/DeepIM/toolkit/../data/LINEMOD_6D/LM6d_converted/LM6d_refine_syn/image_set/observed/LM6d_data_syn_train_observed_ape.txt'
start  0 ape
Fatal Python error: Couldn't create autoTSSkey mapping

Thread 0x00007fc36b260740 (most recent call first):
  File "/home/anaconda3/lib/python3.7/site-packages/glumpy/app/window/backends/backend_glfw.py", line 213 in __init__
  File "/home/anaconda3/lib/python3.7/site-packages/glumpy/app/__init__.py", line 187 in __new__
  File "/home/Workspace/Project/DeepIM/toolkit/../lib/render_glumpy/render_py.py", line 81 in __init__
  File "toolkit/LM6d_ds_4_gen_rendered.py", line 92 in <module>
Aborted (core dumped)

@wangg12  Do you have any suggestions what I could have done wrong?

**Comment by wangg12** [comment]
Can you check whether your glumpy is working by running `python lib/render_glumpy/render_py_multi.py`?
