### ISSUE TITLE
AssertionError: T_src: [ 0. -0.  0.]

### ISSUE THREAD

**Issue by WinnyWMY** [liyi14/mx-DeepIM#58]
Hi,
 I use our own dataset to train the network. if I use  the rendered synthetic data (rendered like LINEMOD in the toolkit ),  it throws an error :

[0620_164548@module.py:1126] batch 0: lr: 1e-05
No handlers could be found for logger "mxboard.event_file_writer"
[0620_164842@callback.py:38] Epoch[0] Batch [20]        Speed: 1.95 samples/sec Train-Flow_L2Loss=0.088646,     Flow_CurLoss=0.081480,  PointMatchingLoss=27.188629        ,       MaskLoss=2.975275,
[0620_165122@callback.py:38] Epoch[0] Batch [40]        Speed: 2.00 samples/sec Train-Flow_L2Loss=0.078643,     Flow_CurLoss=0.202056,  PointMatchingLoss=26.142830        ,       MaskLoss=2.563728,
[0620_165233@module.py:1126] batch 50: lr: 0.0001
[0620_165358@callback.py:38] Epoch[0] Batch [60]        Speed: 2.04 samples/sec Train-Flow_L2Loss=0.088375,     Flow_CurLoss=0.198291,  PointMatchingLoss=27.310941        ,       MaskLoss=2.198455,
[0620_165422@module.py:1156] Epoch[0] Train-Flow_L2Loss=0.090302
[0620_165422@module.py:1156] Epoch[0] Train-Flow_CurLoss=0.054997
[0620_165422@module.py:1156] Epoch[0] Train-PointMatchingLoss=27.565067
[0620_165422@module.py:1156] Epoch[0] Train-MaskLoss=2.182229
[0620_165422@module.py:1161] Epoch[0] Time cost=516.250
[0620_165423@module.py:184] Saved checkpoint to "./output/deepim_release/deepim_flownet_LM_SIXD_v1_rru_RFMx4_8epoch/train__train_/flownet_SE3_ex_LM6d_v1-0001.param        s"
[0620_165428@module.py:188] Saved optimizer state to "./output/deepim_release/deepim_flownet_LM_SIXD_v1_rru_RFMx4_8epoch/train__train_/flownet_SE3_ex_LM6d_v1-0001.        states"
index:  [106 921 879 797 152 166 715 398 539]
[0620_165430@module.py:1117] ./output/deepim_release/deepim_flownet_LM_SIXD_v1_rru_RFMx4_8epoch/train__train_/flownet_SE3_ex_LM6d_v1
[0620_165431@module.py:1121] Convolution1_bias: [0.03617753] Convolution1_weight: [3.4263556] Convolution2_bias: [0.03685752] Convolution2_weight: [1.5662045] Conv        olution3_bias: [0.03063529] Convolution3_weight: [0.9317245] conv2_bias: [0.5982634] conv2_weight: [11.749178] conv3_1_bias: [0.7615658] conv3_1_weight: [16.34456]         conv3_bias: [0.6672679] conv3_weight: [16.173527] conv4_1_bias: [1.948793] conv4_1_weight: [23.536985] conv4_bias: [0.89222676] conv4_weight: [18.513697] conv5_1_        bias: [2.0275779] conv5_1_weight: [19.685951] conv5_bias: [1.1982151] conv5_weight: [21.362574] conv6_1_bias: [5.012363] conv6_1_weight: [20.931683] conv6_bias: [2        .2112195] conv6_weight: [18.961632] deconv4_bias: [0.00519378] deconv4_weight: [128.16124] deconv5_bias: [0.00520507] deconv5_weight: [158.85732] fc6_bias: [0.0302        7891] fc6_weight: [22.340881] fc7_bias: [0.04155897] fc7_weight: [15.942853] flow_conv1_bias: [0.8465199] flow_conv1_weight: [10.660224] mask_conv3_bias: [0.030274        19] mask_conv3_weight: [0.8610723] mask_upsampling_weight: [10.656252] rot_bias: [0.06562771] rot_weight: [9.382267] trans_bias: [0.06281115] trans_weight: [0.5523        279] upsample_flow5to4_bias: [0.00179582] upsample_flow5to4_weight: [3.343272] upsample_flow6to5_bias: [0.00454597] upsample_flow6to5_weight: [3.324867] upsampling        _weight: [15.070229]
[0620_165431@module.py:1122] batch 0: lr: 0.0001
NO POINT VALID IN MASK rendered
...
NO POINT VALID IN MASK rendered
experiments/deepim/../../lib/pair_matching/RT_transform.py:84: RuntimeWarning: overflow encountered in exp
  z2 = T_src[2] / np.exp(T_delta_1[2])
experiments/deepim/../../lib/pair_matching/RT_transform.py:118: RuntimeWarning: invalid value encountered in double_scalars
  T_delta[0] = T_tgt[0] / T_tgt[2] - T_src[0] / T_src[2]
experiments/deepim/../../lib/pair_matching/RT_transform.py:119: RuntimeWarning: invalid value encountered in double_scalars
  T_delta[1] = T_tgt[1] / T_tgt[2] - T_src[1] / T_src[2]
experiments/deepim/../../lib/pair_matching/RT_transform.py:122: RuntimeWarning: divide by zero encountered in log
  T_delta[2] = np.log(T_src[2] / T_tgt[2])
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
experiments/deepim/../../deepim/operator_py/zoom_mask.py:68: RuntimeWarning: invalid value encountered in float_scalars
  obj_rendered_c_x = obj_rendered_c[0] / obj_rendered_c[2]
experiments/deepim/../../deepim/operator_py/zoom_mask.py:69: RuntimeWarning: invalid value encountered in float_scalars
  obj_rendered_c_y = obj_rendered_c[1] / obj_rendered_c[2]
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
NO POINT VALID IN MASK rendered
Error in CustomOp.forward: Traceback (most recent call last):
  File "/home/hao/anaconda3/envs/python27/lib/python2.7/site-packages/mxnet/operator.py", line 989, in forward_entry
    aux=tensors[4])
  File "experiments/deepim/../../deepim/operator_py/transform3d.py", line 88, in forward
    T_src[i].asnumpy(), T_delta[i].asnumpy(), self.T_means, self.T_stds, rot_coord=self.rot_coord
  File "experiments/deepim/../../lib/pair_matching/RT_transform.py", line 81, in T_transform
    assert T_src[2] != 0, "T_src: {}".format(T_src)
AssertionError: T_src: [ 0. -0.  0.]

@wangg12  @liyi14  Any idea what's going on?

Thank you!

**Comment by wangg12** [comment]
Hi, you might need to check the input images and labels, for example, by visualizing them before zoom in and after zoom in.

**Comment by WinnyWMY** [comment]
@wangg12 
感谢答复，可视化结果如下：
![1](https://user-images.githubusercontent.com/19200133/85257243-1b0bac80-b498-11ea-9164-d81c8d469b0e.jpg)
![2](https://user-images.githubusercontent.com/19200133/85257303-31b20380-b498-11ea-99bc-1db907ec3622.jpg)
看起来zoom in效果不明显，是否zoom in中哪里的参数需要调整？
我的图片尺寸是458*458，模型实际直径是551mm

另外，在制作合成图片时，还遇到生成的observed/00xxxx-color.png中有的图片中没有物体或只有部分物体，如下图：
![009979-color](https://user-images.githubusercontent.com/19200133/85257908-20b5c200-b499-11ea-93ca-d4fb22fd5484.png)
我将LM6d_ds_0_gen_observed_poses.py第220行中48改为150，才能使图片上都能投影上物体，不知道这样修改是否可以？
while deg > deg_max or not (**150** < center_x < (width - **150**) and **150** < center_y < (height - **150**))

**Comment by wangg12** [comment]
rendered图片zoom in之后应该是物体的3D中心点的投影点在图片中心，你这里的可视化说明是有问题的。可能是由于你的输入尺寸不一样，目前的代码只支持480x640的图片，如果用到458x458, 需要改代码或者把你的数据预处理成480x640.

**Comment by WinnyWMY** [comment]
不好意思，是我的3D模型中心点不在世界坐标系原点导致投影点不在图片中心的，已修改成用3D模型实际中心点坐标来投影，zoom in是正常的了。

另外，还有三个问题请教下：
1、我的3D模型中心点不在世界坐标系原点，除了计算中心点的投影点外，是否会有其它影响？

2、如果3D模型没有纹理，能正确渲染吗？看代码中render_machine初始化时需要Loading texture？如果没有texture_map.png，怎样做渲染？对网络结果会有影响吗？

3、test阶段，如果只有pose，没有label( the predicted semantic masks)，是否可以？

**Comment by wangg12** [comment]
1.让模型中心点在物体坐标系原点应该就行了, pose也应该是object到camera之间的变换, 这样的话就和世界坐标系原点没关系
2. 我们的渲染代码需要有一个纹理图片，如果没有可以用物体表面颜色生成灰度图纹理，或者换其他的渲染器
3. 有pose和模型，可以生成mask

**Comment by WinnyWMY** [comment]
谢谢，

我用自己的数据按照iter=4 epoch=8训练，但测试结果pose refine的效果不太理想：
目前我只用了一个3D model，训练数据集有10030张图片，其中10000张为合成图片，其余30张是用3张真实图片中每个物体gt_pose周围生成10个随机pose得到的。 跑完8个epoch后得到LOSS结果如下：
Train-Flow_L2Loss=0.208765,	  Flow_CurLoss=0.075474,    PointMatchingLoss=4.011468,	MaskLoss=0.276479,
pointMatchingLoss是从30几降到4左右，从第6个epoch后就一直保持在4左右，无法再继续降低。
测试时还发现test_iter1的结果相对来说是最好的（与gt_pose相差较远），test_iter3、test_iter4反而误差越来越大。

请问可能会有哪些原因导致这些问题？可以从哪些方向调整？

**Comment by wangg12** [comment]
合成图片可能与真实图片相差较大。如果在一部分合成图片上测试，效果没问题，说明能训练成功。在真实图片上测试需要考虑domain gap的问题。

**Comment by WinnyWMY** [comment]
尝试用真实图片和合成图片分别训练，然后用训练集再测试，结果都不是很理想。看loss都有下降，但是网络应该没有收敛。猜测可能我的数据与LINEMOD有差异，哪里处理得不合适？


关于训练和数据处理还有如下几个问题：

1、4次iter之间怎么保证网络朝正确的方向训练？比如iter1输出的refined pose如果偏差很大，这样的pose再作为iter2的输入，不会导致最后的结果越来越差吗？
我的数据在训练过程中会出现iter后pose偏差越来越大，导致下一个iter输入的rendered image中没有物体或只能投影上部分物体。这种情况是openGL渲染的问题吗？是否要把Zfar设置得大一些？我的数据拍摄距离比LINEMOD远

2、flownet模块，我用python lib/flow_c/flow.py测试，报出找不到.gpu_flow的包，应该是flow_c未安装好吧，训练时正常是不是应该显示如下flow_loss =0：
flow weights:  (458, 458) [False]
image_rendered:  (458, 458, 3) 0.016941175 1.0943569
est_loss: 0.0
act_loss: 0.0
但是有的数据上却能得到flow_loss值：
flow weights:  (458, 458) [False  True]
image_rendered:  (458, 458, 3) 0.016941175 1.0943569
est_loss: 714623.6875
act_loss: 270814.46875
比如我在生成render pose的translation时如果修改高斯噪声的标准差，或者不加高斯噪声，flow_loss会出现0，如果按照和LINEMOD一样的高斯噪声，就会有flow_loss值。出现flow_loss=0的数据中还会出现zoom in后物体中心不在图片中心位置。
为什么有的数据上能计算出flow_loss，有的数据是0？

3、zoom in部分还有一个问题，如果image_render与image_real中物体相隔较远，crop后再放大，zoom in 的效果不明显，如下图，这样会影响结果吗？这种情况可以怎么调整呢？我现在是把center_x和center_y在图像中的位置限制在很小的范围内，来尽量接近物体的真实位置，但这样还是无法保证所有图片都能zoom in得很好。
![zoomin](https://user-images.githubusercontent.com/19200133/87025042-736ada00-c20c-11ea-8344-dd7a2e8724b6.jpg)

**Comment by wangg12** [comment]
1. 可以在训练的前期只使用较少的iter数；初始姿态的分布可能要根据你的数据分布情况调整；渲染器zFar默认是6m, 可根据实际情况调整。
2. 建议利用gpu flow的测试代码确保flow的计算是正确的，或者不加flow训练
3. 相隔较远的情况可能需要调整t的初始分布

**Comment by Hao-HUST** [comment]
> rendered图片zoom in之后应该是物体的3D中心点的投影点在图片中心，你这里的可视化说明是有问题的。可能是由于你的输入尺寸不一样，目前的代码只支持480x640的图片，如果用到458x458, 需要改代码或者把你的数据预处理成480x640.

If the image size is 458x458, we only need to modify the  image resolution-revelent code from 480x640 to 458x458? 

I mean, for the download flownet model, is that possible to modify the imput image resolution, or the resolution is fixed(480*640) for the flownet model file?

**Comment by wangg12** [comment]
It is possible to use other resolutions other than 480x640, but there are many code using the hard-coded 480x640 (eg., do a search of 480 in this repo), so you need to change all of them (and probably other places related to the size, for example, the flattened conv feature size for pose estimation) to allow arbitrary sizes.
