### ISSUE TITLE
sh prepare_data.sh problem

### ISSUE THREAD

**Issue by darewolf007** [liyi14/mx-DeepIM#60]
when i run sh prepare_data.sh problem  i get
Traceback (most recent call last):
  File "toolkit/LM6d_0_gen_gt_observed.py", line 188, in <module>
    gen_gt_observed()
  File "toolkit/LM6d_0_gen_gt_observed.py", line 105, in gen_gt_observed
    render_machine = Render_Py(model_dir, K, width, height, ZNEAR, ZFAR)
  File "/home/haowen/study code/mx-DeepIM/toolkit/../lib/render_glumpy/render_py.py", line 70, in __init__
    self.window = app.Window(width=width, height=height, visible=False)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/site-packages/glumpy/app/__init__.py", line 151, in __new__
    backend = use(name)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/site-packages/glumpy/app/__init__.py", line 117, in use
    importlib.import_module(name)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/haowen/.conda/envs/py36/lib/python3.6/site-packages/glumpy/app/window/backends/backend_glfw.py", line 86, in <module>
    from glumpy.ext import glfw
  File "/home/haowen/.conda/envs/py36/lib/python3.6/site-packages/glumpy/ext/glfw.py", line 544, in <module>
    glfwSetWindowMonitor           = _glfw.glfwSetWindowMonitor
  File "/home/haowen/.conda/envs/py36/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libglfw.so.3.1: undefined symbol: glfwSetWindowMonitor
Exception ignored in: <bound method Render_Py.__del__ of <lib.render_glumpy.render_py.Render_Py object at 0x7f9266657f28>>
Traceback (most recent call last):
  File "/home/haowen/study code/mx-DeepIM/toolkit/../lib/render_glumpy/render_py.py", line 110, in __del__
    self.window.close()
AttributeError: 'Render_Py' object has no attribute 'window'

i do the echo $DISPLAY , got : 0
but when i run python render_py_multi.py
the problem is AttributeError: 'Render_Py' object has no attribute 'window'

**Comment by wangg12** [comment]
@darewolf007 Hi, you must have a monitor connected to your computer.

**Comment by darewolf007** [comment]
i have a monitor ,i download glumpy from github i run the example ,also the same problem ,i run NVIDIA-settings also get problem ,is there something wrong with my NVIDIA drive

**Comment by darewolf007** [comment]
i still have the problem , NVIDIA is fine

**Comment by wangg12** [comment]
Could you try running some examples of glumpy: for example `app-two-programs.py` or `app-simple.py`?

**Comment by wangg12** [comment]
@darewolf007 Could you try using glumpy at this commit: `5ca21505b9b65549b8f9fa8ddb3a700c75119d61`?

**Comment by darewolf007** [comment]
oh,thank you , i uninstall the glumpy and miraculous the error has been solved,but I run the example render_py_multi.py , i got other problem 
self.window:  <GLFW.Window object at 0x7f8bb112d9e8>
self.render_kernel at init:  [<glumpy.gloo.program.Program object at 0x7f8bb46a85f8>]
Traceback (most recent call last):
  File "render_py_multi.py", line 224, in <module>
    pose_real_est = np.loadtxt(pose_path.format(cur_class, cur_img_idx), skiprows=1)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: /home/haowen/study code/mx-DeepIM/lib/render_glumpy/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/gt_observed/driller/000001-pose.txt not found
can i ignore this error?and i want to ask the folder named benchviseblue whether need to be renamed as benchvise?

**Comment by wangg12** [comment]
If you just want to verify the renderer, you can ignore the error.
You can keep both benchviseblue and benchvise, by  using soft link.

**Comment by darewolf007** [comment]
thank you for your suggestion ! 
I  also want to ask when i finish the prepare_data.sh progress , can i move the whole project to another computer with final data folder ? It seems that running sh prepare_data.sh  would take a long time.

**Comment by wangg12** [comment]
I think you can do it.

**Comment by darewolf007** [comment]
hello , i get another question. 
I build a soft link for the folder of data, 
but when i run python experiments/deepim/deepim_train_test.py --cfg experiments/deepim/cfgs/deepim_flownet_LM_SIXD_v1_ape_RFMx4_8epoch.yaml --gpus 0 
i get the 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/haowen/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "experiments/deepim/../../lib/pair_matching/data_pair.py", line 155, in get_data_pair_train_batch
    pairdb, config, scale_ind_list, phase="train", random_k=random_k
  File "experiments/deepim/../../lib/utils/image.py", line 261, in get_pair_mask
    assert fg.any(), "NOT_VALID: {}, {}".format(mask_gt_observed_path, np.unique(fg))
AssertionError: NOT_VALID: ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/observed/01/000891-label.png, [False]
"""
Is that i make a wrong soft link? I can fing the png in the folder

**Comment by wangg12** [comment]
@darewolf007 Thanks for reporting this. It seems this is a bug, could you update with the master's code and try again?
You need to re-run this: `python toolkit/LM6d_devkit/LM6d_2a_adapt_images.py`

**Comment by darewolf007** [comment]
I have re-run it, now the result is
/home/haowen/.conda/envs/py36/lib/python3.6/site-packages/scipProcess ForkPoolWorker-1:
已放弃 (核心已转储)
 Traceback (most recent call last):
  File "/home/haowen/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/haowen/.conda/envs/py36/lib/python3.6/multiprocessing/queues.py", line 354, in put
    self._writer.send_bytes(obj)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/haowen/.conda/envs/py36/lib/python3.6/multiprocessing/connection.py", line 398, in _send_bytes
    self._send(buf)
  File "/home/haowen/.conda/envs/py36/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by wangg12** [comment]
I don't know what is wrong here. Maybe you can try to debug into the dataloader, for example:
https://github.com/liyi14/mx-DeepIM/blob/3b06bd0f778481b7b3acb3cf035e4d438290f6ca/deepim/core/loader.py#L289

**Comment by darewolf007** [comment]
OK ,I  will try ,thank you !
